### ISSUE TITLE
Wonder Woman

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [claustromaniac/Compare-UserJS#10]
I didn't read the readme 100% because, IDK, I'm lazy. But would it be prudent to let people knwo that if they get a error like the one below, to not use spaces in their paths

![wonderwoman](https://user-images.githubusercontent.com/16656956/49340454-f04ccf80-f637-11e8-913b-b51f0819e5d8.png)

PS: I have no idea if it has problems with spaces in file names, because I'm too lazy to test it :kiss:

**Comment by Thorin-II** [comment]
Yup, this is for the current version

**Comment by claustromaniac** [comment]
It was a different issue than the one I mentioned before. Thanks :jeans:

**Comment by Thorin-II** [comment]
No worries ~~man~~ .. err, I mean [cat](https://thechive.files.wordpress.com/2018/08/cat-saturday-31-photos-251.jpg)
