### ISSUE TITLE
@earthlng's thing bitching about "Collections not found"

### ISSUE THREAD

**Issue by claustromaniac** [claustromaniac/Compare-UserJS#11]
@earthlng does [this version](https://github.com/claustromaniac/Compare-UserJS/tree/93174b386024b188a600a9813750bf50ce82aec2) work for you?

If that is not the case, does [this one](https://github.com/claustromaniac/Compare-UserJS/tree/8a5008d1e74b5255202e0e7887b0d851b06380ea)?

[reference link](https://github.com/ghacksuserjs/ghacks-user.js/pull/562#issuecomment-443505374)

**Comment by earthlng** [comment]
bitching? bitch puhlease! it was simply a friendly FYI :)

this one still works: https://github.com/claustromaniac/Compare-UserJS/commit/38e7f34768a8e29a6c25cc5aa8b75fa401157fd4#diff-cab29a3f8309044c0459f253c305fb54

commit that broke it for me: https://github.com/claustromaniac/Compare-UserJS/commit/342bb472523b20fb8642b7c3cbee36aa0cbecaae#diff-cab29a3f8309044c0459f253c305fb54

**Comment by claustromaniac** [comment]
I have some bad news for you: you have .NET installed. Otherwise, no version of the script (or PowerShell itself) would work on your end at all.

~~Try adding `System.` before `Collections.` in~~  EDIT: I did that myself in 658519f

https://github.com/claustromaniac/Compare-UserJS/blob/c04690f8958542031a88938760d9055b4f7e3eab/Compare-UserJS.ps1#L210-L220

If that doesn't work, type this in the PowerShell CLI:
```powershell
$PSVersionTable.CLRVersion
```
It will return the value of that variable. If it is the following (or older)...
```powershell
Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      50727  8762
```
... then you must have disabled .NET 3.5 as a Windows component, or its assemblies aren't loading on your end for some other reason. Before you keep giving me *friendly FYI* (criticizing me for no good reason in the process): .NET 3.5 is a standard Windows 7 component, and the classes used in this script also exist in .NET Core (which is newer, and is the version of .NET available for Linux). The README explicitly states that this script requires PowerShell v2 and, guess what, the earliest version of Windows that comes with PS v2 installed is Win 7. So, adding .NET 3.5 as a dependency is no big deal (if you have Win 7, you have both requirements). I will still edit the README and state that this requires .NET 3.5, just in case.
