### ISSUE TITLE
Single cote seems to make the script fail

### ISSUE THREAD

**Issue by intika** [claustromaniac/Compare-UserJS#13]
Hi bro, 

In my last version of librefox i have some lines with `// Default Value : "` and `// "`

This seem to make the script fail without an error feedback... 

I just removed those single quote lines from my mozilla.cfg file to fix the problem... its just to let you know about it ;) 

Thanks 

MiiiAAAaWWwwwooOOooo :D :+1: 

EDIT : i am still debugging it seem to be related to something else

**Comment by intika** [comment]
Grr still not finding... it could be the length of my script over 3400 lines...

**Comment by intika** [comment]
I did not find what exactly make it fail i think its a combinations of multiple thing in the comments... i am just moving those lines to a separate files... i will comeback here once those will be published ;)

**Comment by claustromaniac** [comment]
Waddup!

I tried comparing your mozilla.cfg to an user.js but I didn't have any issues. I can look for the culprit pretty easily if you give me a sample that doesn't work on your end.

**Comment by intika** [comment]
Yes i removed a whole block of comment/wiki to have it working for users who wants to play with your scripts... i will post when i finish building binaries... it makes me sick :( esr/x64/x32/... all the platforms... i don't know if i will keep that like that... i will close this for the moment and come back with the exact info :)
