### ISSUE TITLE
add switch parameter for writing the output as HTML

### ISSUE THREAD

**Issue by claustromaniac** [claustromaniac/Compare-UserJS#6]
...or some other markup language. I mean, for a few measly extra lines... why the hell not?

**Comment by Thorin-II** [comment]
> .. why the hell not?

https://xkcd.com/1319/ :trollface:

**Comment by Thorin-II** [comment]
cool fact of the day for ya .. the dot above an `i` or `j` is called a TITTLE (stop laughing)

**Comment by claustromaniac** [comment]
ima have to look that up in the Urban Dictionary to confirm something. Added to my TODO list.

As for the xkcd... well, this is legit. It would make visual parsing easier, and it should take just a handful of lines to get it rolling. About 5 according to my estimation, without looking at the code. That's of course **if** I take the simplest route, but I think adding some pretty CSS in the output would be nice, and it wouldn't take many extra lines. I could even write TWO styles, and add an EXTRA switch parameter for toggling dark/light mode. Even better: if I'm already including CSS, why not provide it in separate files instead of embedding it, to make it more modular? It would only take another couple short steps from there, and users would then be able to write _their own styles_ if they wanted! While I'm at it, I could even add some good ol' JavaScript in, to add controls for filtering the output and all. Sounds great, doesn't it?! But, something bugs me: if I'm already dealing with HTML + CSS + Javascript, why not turn the whole thing into a WEB APP? I mean, just think of the possibilities man!!!

### **. . .**

EDIT: upon re-reading this I'm getting worried it almost doesn't even sound like I'm joking anymore.

**Comment by Thorin-II** [comment]
+1 for the WEB APP

**Comment by Thorin-II** [comment]
:cat2: .. u still alive there buddy ... I'm concerned for your safety ... the last commit was a week ago. Have you been trapped in the neighbor's garage or something? Please advise

**Comment by claustromaniac** [comment]
Aww. The pants missed me! Sorry, I got myself stuck in a toilet paper tube for so many days that I look smaller now. I was also ill for a few days, and after that I just got lost in my research of random stuff of questionable usefulness!

I suspect this issue will remain open for some time... :laughing:

**Comment by Thorin-Oakenpants** [comment]
readme: 
> Additionally, it can catch one type of syntax error (for now), and include**s** that information in the report

includes should be singular

**Comment by Thorin-II** [comment]
claustromaniac .. is this you: https://thechive.files.wordpress.com/2018/08/daily_picdump_2917_640_high_15.jpg :grinning:
